name: Check PHP-WASM updates
on:
  # manually
  workflow_dispatch:
  # also on webhooks
  repository_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '32 * * * *'

jobs:
  build:
    name: Check update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clone drupal cms
        run: |
          git clone https://git.drupalcode.org/project/drupal_cms.git
      - name: Install dependencies in trial
        run: |
          cd drupal_cms/trial
          npm ci
      - name: Find latest version
        run: |
          export latest_version=$(npm view php-wasm-zlib --json | jq -r '.time | to_entries | last | .key')
          # Try to install it, and see if we have a diff
          npm i php-wasm-zlib@$latest_version -S --save-exact
          git diff --exit-code > /dev/null
          if [ $? -ne 0 ]; then
            export $packages_to_install=$(cat package.json | jq -r '.devDependencies | to_entries | .[].key' | grep php)
            # Loop through each line in the variable
            echo "$packages_to_install" | while IFS= read -r package; do
              # Execute your command with the current line
              echo "Installing: $package"
              npm i $package -S --save-exact
            done
            git diff
            exit 1
          else
            exit 0
          fi
